### ISSUE TITLE
Incorrect configuration option prefix

### ISSUE THREAD

**Issue by Gert-dev** [mallardduck/linter-phpstan#2]
Hello

Just wanted to let you know that I think you forgot to update the configuration option prefix containing the package name in `Main.js`; it still says `atom-linter-phpstan.autoConfigSearch` instead of `linter-phpstan.autoConfigSearch`.

These handlers don't appear to ever be executed currently, resulting in `this.autoExecutableSearch` to never be set.

**Comment by mallardduck** [comment]
🙏 Thank you!

**Comment by mallardduck** [comment]
I've made some adjustments but will have to test later tonight.
Unless someone shoots a PR over I won't push another tag/release until I can properly test.

**Comment by Gert-dev** [comment]
No problem! Thanks for taking the time to update the PHPStan support for Atom!

**Comment by mallardduck** [comment]
Absolutely - it's the least I can do especially with home much I rely on php-ide-serenata! I just pushed v1.0.6 after I was able to test things and they all seem working to me. Let me know if there are any issues on your end.

I'm not super knowledgeable on Atom development yet. So I don't have any huge plans or ideas, but I'm open for ideas. I think it would be cool if this package would work similarly to serenata - that way they feel well integrated.

The first idea that comes to mind might be having this package utilize project-manager as Serenata does. That way the linter could be configured on a project basis.

**Comment by Gert-dev** [comment]
Thanks! Everything seems to be working fine, now. This will certainly ease the setup of PHPStan for new adopters or existing users alike without needing to manually patch the `--error-format` option anymore.

For Serenata I'm trying to migrate away from project-manager for the upcoming version that uses version 5.0 of the server; not that I have any beef with project-manager, it's just one less forced dependency for users to install - and perhaps these users like different project managers.

project-manager had the interesting concept of having per-project configuration, though, but it can't work without other packages adopting it and there being some kind of a standard. I hoped this would be the case as Serenata evolved, but few other packages seem to have adopted it. I think a [proper implementation in Atom would probably be a better course of action for the future](https://github.com/atom/atom/pull/16698). If this pull request makes it in, package authors won't need to do a lot to support project-specific configurations, users can just configure their package settings on a per-project basis automatically.
